# Generated by Django 4.1.6 on 2023-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
