# Generated by Django 4.1.6 on 2023-03-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_roomusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusers',
            name='sentiment',
            field=models.TextField(default='dummy'),
            preserve_default=False,
        ),
    ]
